const assets = [
	{
	"id":"achievments",
	"url":"assets/json\\achievments.json"
	},
	{
	"id":"config",
	"url":"assets/json\\config.json"
	},
	{
	"id":"localization_DE",
	"url":"assets/json\\localization_DE.json"
	},
	{
	"id":"localization_EN",
	"url":"assets/json\\localization_EN.json"
	},
	{
	"id":"localization_ES",
	"url":"assets/json\\localization_ES.json"
	},
	{
	"id":"localization_FR",
	"url":"assets/json\\localization_FR.json"
	},
	{
	"id":"localization_IT",
	"url":"assets/json\\localization_IT.json"
	},
	{
	"id":"localization_JA",
	"url":"assets/json\\localization_JA.json"
	},
	{
	"id":"localization_KO",
	"url":"assets/json\\localization_KO.json"
	},
	{
	"id":"localization_PT",
	"url":"assets/json\\localization_PT.json"
	},
	{
	"id":"localization_RU",
	"url":"assets/json\\localization_RU.json"
	},
	{
	"id":"localization_TR",
	"url":"assets/json\\localization_TR.json"
	},
	{
	"id":"localization_ZH",
	"url":"assets/json\\localization_ZH.json"
	},
	{
	"id":"modifyers",
	"url":"assets/json\\modifyers.json"
	},
	{
	"id":"player-assets",
	"url":"assets/json\\assets\\player-assets.json"
	},
	{
	"id":"cards",
	"url":"assets/json\\cards\\cards.json"
	},
	{
	"id":"companion-animation",
	"url":"assets/json\\animation\\companion-animation.json"
	},
	{
	"id":"entity-animation",
	"url":"assets/json\\animation\\entity-animation.json"
	},
	{
	"id":"player-animation",
	"url":"assets/json\\animation\\player-animation.json"
	},
	{
	"id":"body-parts",
	"url":"assets/json\\database\\body-parts.json"
	},
	{
	"id":"starter-inventory",
	"url":"assets/json\\database\\starter-inventory.json"
	},
	{
	"id":"game-shop",
	"url":"assets/json\\economy\\game-shop.json"
	},
	{
	"id":"enemy-wave-001",
	"url":"assets/json\\enemy-waves\\enemy-wave-001.json"
	},
	{
	"id":"enemy-wave-01",
	"url":"assets/json\\enemy-waves\\enemy-wave-01.json"
	},
	{
	"id":"enemy-wave-02",
	"url":"assets/json\\enemy-waves\\enemy-wave-02.json"
	},
	{
	"id":"enemy-wave-03",
	"url":"assets/json\\enemy-waves\\enemy-wave-03.json"
	},
	{
	"id":"enemy-wave-04",
	"url":"assets/json\\enemy-waves\\enemy-wave-04.json"
	},
	{
	"id":"enemy-wave-tutorial",
	"url":"assets/json\\enemy-waves\\enemy-wave-tutorial.json"
	},
	{
	"id":"waves2",
	"url":"assets/json\\enemy-waves\\waves2.json"
	},
	{
	"id":"wavesBkp",
	"url":"assets/json\\enemy-waves\\wavesBkp.json"
	},
	{
	"id":"companions",
	"url":"assets/json\\entity\\companions.json"
	},
	{
	"id":"enemies",
	"url":"assets/json\\entity\\enemies.json"
	},
	{
	"id":"player",
	"url":"assets/json\\entity\\player.json"
	},
	{
	"id":"level-001",
	"url":"assets/json\\environment\\level-001.json"
	},
	{
	"id":"level-1",
	"url":"assets/json\\environment\\level-1.json"
	},
	{
	"id":"level-2",
	"url":"assets/json\\environment\\level-2.json"
	},
	{
	"id":"level-3",
	"url":"assets/json\\environment\\level-3.json"
	},
	{
	"id":"level-4",
	"url":"assets/json\\environment\\level-4.json"
	},
	{
	"id":"level-tutorial",
	"url":"assets/json\\environment\\level-tutorial.json"
	},
	{
	"id":"acessories",
	"url":"assets/json\\misc\\acessories.json"
	},
	{
	"id":"attachments",
	"url":"assets/json\\misc\\attachments.json"
	},
	{
	"id":"attribute-modifiers",
	"url":"assets/json\\misc\\attribute-modifiers.json"
	},
	{
	"id":"buff-debuff",
	"url":"assets/json\\misc\\buff-debuff.json"
	},
	{
	"id":"general-vfx",
	"url":"assets/json\\vfx\\general-vfx.json"
	},
	{
	"id":"particle-behaviour",
	"url":"assets/json\\vfx\\particle-behaviour.json"
	},
	{
	"id":"particle-descriptors",
	"url":"assets/json\\vfx\\particle-descriptors.json"
	},
	{
	"id":"weapon-vfx-pack",
	"url":"assets/json\\vfx\\weapon-vfx-pack.json"
	},
	{
	"id":"weapon-vfx",
	"url":"assets/json\\vfx\\weapon-vfx.json"
	},
	{
	"id":"main-weapons",
	"url":"assets/json\\weapons\\main-weapons.json"
	},
	{
	"id":"weapon-in-game-visuals",
	"url":"assets/json\\weapons\\weapon-in-game-visuals.json"
	},
	{
	"id":"weapon-view-overriders",
	"url":"assets/json\\weapons\\weapon-view-overriders.json"
	}
];

export default assets;
