const assets = [
	{
	"id":"achievments",
	"url":"assets/json\\achievments.json"
	},
	{
	"id":"enemies1",
	"url":"assets/json\\enemies1.json"
	},
	{
	"id":"localization_DE",
	"url":"assets/json\\localization_DE.json"
	},
	{
	"id":"localization_EN",
	"url":"assets/json\\localization_EN.json"
	},
	{
	"id":"localization_ES",
	"url":"assets/json\\localization_ES.json"
	},
	{
	"id":"localization_FR",
	"url":"assets/json\\localization_FR.json"
	},
	{
	"id":"localization_IT",
	"url":"assets/json\\localization_IT.json"
	},
	{
	"id":"localization_JA",
	"url":"assets/json\\localization_JA.json"
	},
	{
	"id":"localization_KO",
	"url":"assets/json\\localization_KO.json"
	},
	{
	"id":"localization_PT",
	"url":"assets/json\\localization_PT.json"
	},
	{
	"id":"localization_RU",
	"url":"assets/json\\localization_RU.json"
	},
	{
	"id":"localization_TR",
	"url":"assets/json\\localization_TR.json"
	},
	{
	"id":"localization_ZH",
	"url":"assets/json\\localization_ZH.json"
	},
	{
	"id":"modifyers",
	"url":"assets/json\\modifyers.json"
	},
	{
	"id":"mainWeapons",
	"url":"assets/json\\weapons\\mainWeapons.json"
	},
	{
	"id":"entity-ss-vfx",
	"url":"assets/json\\vfx\\entity-ss-vfx.json"
	},
	{
	"id":"entity-particle-descriptor",
	"url":"assets/json\\vfx\\entity-particle-descriptor.json"
	},
	{
	"id":"weapon-ss-vfx-packs",
	"url":"assets/json\\vfx\\weapon-ss-vfx-packs.json"
	},
	{
	"id":"weapon-ss-vfx",
	"url":"assets/json\\vfx\\weapon-ss-vfx.json"
	}
];

export default assets;
